name: PoC - Token Permissions Test

on:
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
      - name: Show default token permissions
        run: |
          echo "Listing permissions of GITHUB_TOKEN"
          curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=test" || true

      - name: Try pushing a dummy file
        run: |
          echo "PoC file" > poc.txt
          git config --global user.email "poc@example.com"
          git config --global user.name "PoC Bot"
          git init
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git checkout -b poc-branch
          git add poc.txt
          git commit -m "PoC commit via GITHUB_TOKEN"
          git push origin poc-branch
